/*
 * Spaceflight News API
 * The Spaceflight News API (SNAPI) is a product by [The Space Devs](https://thespacedevs.com) (TSD). It's the most complete and up-to-date spaceflight news API currently available.  While this API is **free to use**, we do encourage developers to support us through [Patreon](https://www.patreon.com/TheSpaceDevs) to keep the API up and running.   ### FAQs & Tutorials   - [GitHub repository](https://github.com/TheSpaceDevs/Tutorials/): contains FAQs and tutorials for TSD APIs   - [TSD FAQ](https://github.com/TheSpaceDevs/Tutorials/blob/main/faqs/faq_TSD.md): TSD-specific FAQ (e.g. history, network, funding, etc.)   - [SNAPI FAQ](https://github.com/TheSpaceDevs/Tutorials/blob/main/faqs/faq_SNAPI.md): SNAPI-specific FAQ   ### Feedback & Support   If you need any help with SNAPI, you can ask in the [`💬feedback-and-help`](https://discord.com/channels/676725644444565514/1019976345884827750) forum of the TSD [Discord server](https://discord.gg/p7ntkNA) or email [derk@spaceflightnewsapi.net](mailto:derk@spaceflightnewsapi.net).
 *
 * The version of the OpenAPI document: 4.8.3 (v4)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.aplazuk.homewrok7news.model;



import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import org.springframework.web.util.UriComponentsBuilder;

import java.net.URI;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.*;

/**
 * Article
 */

public class Article {
    @NotNull(message = "Id cannot be null")
    private Integer id;
    @NotBlank(message = "Please provide valid news tittle")
    private String title;
    @NotNull(message = "Url cannot be null")
    private URI url;
    @JsonProperty("image_url")
    @NotNull(message = "Image Url cannot be null")
    private URI imageUrl;
    @JsonProperty("news_site")
    @NotBlank(message = "Please provide valid news site")
    private String newsSite;
    @NotBlank(message = "Please provide valid news summary")
    private String summary;
    @JsonProperty("published_at")
    @NotNull(message = "Published date cannot be null")
    private OffsetDateTime publishedAt;
    @JsonProperty("updated_at")
    private OffsetDateTime updatedAt;
    private Boolean featured;
    private List<Launch> launches;
    private List<Event> events;

    public Article() {
    }

    public Article(Integer id, String title, String url, String imageUrl, String newsSite, String summary, LocalDateTime publishedAt) {
        this.id = id;
        this.title = title;
        this.url = UriComponentsBuilder.fromUriString(url).build().toUri();
        this.imageUrl = UriComponentsBuilder.fromUriString(imageUrl).build().toUri();
        this.newsSite = newsSite;
        this.summary = summary;
        this.publishedAt = publishedAt.atOffset(ZoneOffset.UTC);
    }


    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public URI getUrl() {
        return url;
    }

    public void setUrl(URI url) {
        this.url = url;
    }

    public URI getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(URI imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getNewsSite() {
        return newsSite;
    }

    public void setNewsSite(String newsSite) {
        this.newsSite = newsSite;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public OffsetDateTime getPublishedAt() {
        return publishedAt;
    }

    public void setPublishedAt(OffsetDateTime publishedAt) {
        this.publishedAt = publishedAt;
    }

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Boolean getFeatured() {
        return featured;
    }

    public void setFeatured(Boolean featured) {
        this.featured = featured;
    }

    public List<Launch> getLaunches() {
        return launches;
    }

    public void setLaunches(List<Launch> launches) {
        this.launches = launches;
    }

    public List<Event> getEvents() {
        return events;
    }

    public void setEvents(List<Event> events) {
        this.events = events;
    }
}